# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b62e6f48624663e5b48722e72c8640c31af4a4ed00e83a02e6588c2622b14fd00d5ed103f95722cf673c19e1bdecc590bad93a01af392dd8e1b0329f9c7a054

test:
  secret_key_base: 83fcc9a7139ee1e186fc6de5df4df1a5a6a76324525b2f523ab7fd55fe3f7191ede758570ed2676886a192923f54c776ee29614b728daf28c6caa4c48ab8d226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
