# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d7078d377972d1b6624884914313141408aa6a4565644580ed9b31b404b1378a7def64245109e4b0412fa728b1ea47f2694321a334538a2033e24d9a993bcd

test:
  secret_key_base: 13755dc89e4879aa820f89dba9658653e0c9e302102abd1dd4a827947fcec0a863da9c67e095a8b54c5f2405aa15313fcb3cb2fcebaf8d62f6a70395e68936de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
